#!/usr/bin/env Rscript

library(devtools)
library(BBmisc)

deps = as.package(".")[c("imports", "depends", "suggests", "linkingto")]
deps = lapply(Filter(Negate(is.null), deps), parse_deps)
deps = subset(do.call(rbind, deps), select=c("name", "version"))
rownames(deps) = NULL

installed = installed.packages(fields=c("Package", "Version"))[, c("Package", "Version")]
deps$installed = installed[, "Version"][match(deps$name, installed[, "Package"], nomatch=NA_character_)]

install = unlist(rowLapply(deps, function(r) {
  if (is.na(r$installed))
    return(TRUE)
  if (!is.na(r$version) && package_version(r$version) > package_version(r$installed))
    return(TRUE)
  return(FALSE)
}))

if (any(install))
  install.packages(deps$name[install])

# vim: ft=r
