context("single-objective test functions")

test_that("single-objective test function generators work", {
    expectIsSnoofFunction = function(obj, generator) {
        expect_is(obj, c("smoof_function", "function"), info = "No snoof function generated by '%s'", generator)
    }

    # get all relevant methods
    all.methods = unclass(lsf.str(envir = asNamespace("smoof"), all = TRUE))
    fun.generators = all.methods[grep("^make.*Function$", all.methods)]

    # filter internal stuff
    fun.generators = setdiff(fun.generators,
        c("makeSingleObjectiveFunctionFromSOOFunction",
            "makeSingleObjectiveFunction",
            "makeMultiObjectiveFunction", "makeInternalObjectiveFunction",
            "makeObjectiveFunction"
        )
    )

    # filter unexported
    fun.generators = setdiff(fun.generators, c("makeKeaneFunction", "makeKatsuuraFunction"))

    for (fun.generator in fun.generators) {
        fun = try(do.call(fun.generator, list()), silent = TRUE)
        if (inherits(fun, "try-error")) {
            fun = do.call(fun.generator, list(dimensions = 2L))
        }
        expectIsSnoofFunction(fun, fun.generator)
        test.param = ParamHelpers::sampleValues(getParamSet(fun), 1L)
        test.val = fun(test.param)
        expect_true(is.numeric(test.val))
    }

    expect_true(length(filterFunctionsByTags("continous")) > 0L)
})