// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// dtlz_1
SEXP dtlz_1(arma::vec x, int M);
RcppExport SEXP smoof_dtlz_1(SEXP xSEXP, SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    __result = Rcpp::wrap(dtlz_1(x, M));
    return __result;
END_RCPP
}
// dtlz_2
SEXP dtlz_2(arma::vec x, int M);
RcppExport SEXP smoof_dtlz_2(SEXP xSEXP, SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    __result = Rcpp::wrap(dtlz_2(x, M));
    return __result;
END_RCPP
}
// dtlz_3
SEXP dtlz_3(arma::vec x, int M);
RcppExport SEXP smoof_dtlz_3(SEXP xSEXP, SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    __result = Rcpp::wrap(dtlz_3(x, M));
    return __result;
END_RCPP
}
// dtlz_4
SEXP dtlz_4(arma::vec x, int M, double alpha);
RcppExport SEXP smoof_dtlz_4(SEXP xSEXP, SEXP MSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    __result = Rcpp::wrap(dtlz_4(x, M, alpha));
    return __result;
END_RCPP
}
// dtlz_5
SEXP dtlz_5(arma::vec x, int M);
RcppExport SEXP smoof_dtlz_5(SEXP xSEXP, SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    __result = Rcpp::wrap(dtlz_5(x, M));
    return __result;
END_RCPP
}
// dtlz_6
SEXP dtlz_6(arma::vec x, int M);
RcppExport SEXP smoof_dtlz_6(SEXP xSEXP, SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    __result = Rcpp::wrap(dtlz_6(x, M));
    return __result;
END_RCPP
}
