# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

evaluateBBOBFunctionCPP <- function(dimension, fid, iid, x) {
    .Call('smoof_evaluateBBOBFunctionCPP', PACKAGE = 'smoof', dimension, fid, iid, x)
}

getOptimumForBBOBFunctionCPP <- function(dimension, fid, iid) {
    .Call('smoof_getOptimumForBBOBFunctionCPP', PACKAGE = 'smoof', dimension, fid, iid)
}

