# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dtlz_1 <- function(x, M) {
    .Call(`_smoof_dtlz_1`, x, M)
}

dtlz_2 <- function(x, M) {
    .Call(`_smoof_dtlz_2`, x, M)
}

dtlz_3 <- function(x, M) {
    .Call(`_smoof_dtlz_3`, x, M)
}

dtlz_4 <- function(x, M, alpha = 100) {
    .Call(`_smoof_dtlz_4`, x, M, alpha)
}

dtlz_5 <- function(x, M) {
    .Call(`_smoof_dtlz_5`, x, M)
}

dtlz_6 <- function(x, M) {
    .Call(`_smoof_dtlz_6`, x, M)
}

dtlz_7 <- function(x, M) {
    .Call(`_smoof_dtlz_7`, x, M)
}

mof_ED_1 <- function(x, m, gamma, theta) {
    .Call(`_smoof_mof_ED_1`, x, m, gamma, theta)
}

mof_ED_2 <- function(x, m, gamma, theta) {
    .Call(`_smoof_mof_ED_2`, x, m, gamma, theta)
}

kursawe <- function(x) {
    .Call(`_smoof_kursawe`, x)
}

mof_WFG_1 <- function(z, M, k) {
    .Call(`_smoof_mof_WFG_1`, z, M, k)
}

mof_WFG_2 <- function(z, M, k) {
    .Call(`_smoof_mof_WFG_2`, z, M, k)
}

mof_WFG_3 <- function(z, M, k) {
    .Call(`_smoof_mof_WFG_3`, z, M, k)
}

mof_WFG_4 <- function(z, M, k) {
    .Call(`_smoof_mof_WFG_4`, z, M, k)
}

mof_WFG_5 <- function(z, M, k) {
    .Call(`_smoof_mof_WFG_5`, z, M, k)
}

mof_WFG_6 <- function(z, M, k) {
    .Call(`_smoof_mof_WFG_6`, z, M, k)
}

mof_WFG_7 <- function(z, M, k) {
    .Call(`_smoof_mof_WFG_7`, z, M, k)
}

mof_WFG_8 <- function(z, M, k) {
    .Call(`_smoof_mof_WFG_8`, z, M, k)
}

mof_WFG_9 <- function(z, M, k) {
    .Call(`_smoof_mof_WFG_9`, z, M, k)
}

